name: Create GitHub Release
description: create a GitHub Release and upload artifacts

inputs:
  github_token:
    description: "GitHub token to request GitHub API"
    required: true
  tag:
    description: "The tag name of the release"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Set up Node.js
      uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
      with:
        node-version-file: .tool-versions

    - name: Install dependencies
      shell: bash
      run: npm ci

    - name: Build project
      shell: bash
      run: npm run build

    - name: Zip artifacts
      shell: bash
      run: |
        zip -r notoin-bar-colorize.zip dist/

    - name: Release
      uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2.2.1
      with:
        files: notoin-bar-colorize.zip
        body_path: CHANGELOG.md
        tag_name: ${{ inputs.tag }}
        token: ${{ inputs.github_token }}
