name: Create GitHub Release
description: create a GitHub Release and upload artifacts

inputs:
  github_token:
    description: "GitHub token to request GitHub API"
    required: true
  tag:
    description: "The tag name of the release"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - name: Set up Node.js
      uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
      with:
        node-version-file: .tool-versions

    - name: Install dependencies
      shell: bash
      run: npm ci

    - name: Build project
      shell: bash
      run: npm run build

    - name: Zip artifacts
      shell: bash
      run: |
        zip -r notoin-bar-colorize.zip dist/

    - name: Release
      uses: softprops/action-gh-release@6da8fa9354ddfdc4aeace5fc48d7f679b5214090 # v2.4.1
      with:
        files: notoin-bar-colorize.zip
        body_path: CHANGELOG.md
        tag_name: ${{ inputs.tag }}
        token: ${{ inputs.github_token }}
