name: release

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions: {}
    steps:
      - name: Check ref
        if: |
          !startsWith(github.ref, 'refs/tags/')
        run: |
          echo "This action should only be run on tag"
          exit 1

  release:
    needs: [check]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Release
        uses: ./.github/actions/release
        with:
          tag: ${{ github.ref_name }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
